--PASSO 1 CRIAÇÃO DO DIRETORIO E APONTAMENTO PARA O SO
CREATE OR REPLACE DIRECTORY ESTUDO AS 'C:\estudo';

--PASSO 2 CRIAÇÃO DE ESTRUTURA FISICA NO BD PARA CONSUMIR O ARQUIVO DESEJADO
CREATE TABLE EXTERNAL_ESTUDO 
	( cod		number
	 ,co_name	varchar2(4000)
	 ,partname  varchar2(4000)
	 ,arch_json	varchar2(4000)
	 ,dat_ext   date
	) 
	ORGANIZATION EXTERNAL 
		(	TYPE ORACLE_LOADER 
		 DEFAULT DIRECTORY ESTUDO
		  ACCESS PARAMETERS 
		(
			RECORDS DELIMITED BY NEWLINE
			BADFILE 'logs.bad' 
			LOGFILE 'arch_import.log'
			SKIP 0 
			FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
		) 
		LOCATION
			(
				'import_produt.csv'
			)
	)
REJECT LIMIT UNLIMITED;

--CONSULTANDO NOSSO RESULTADO
SELECT cod
	 , co_name
	 , partname
	 , arch_json
	 , dat_ext
  FROM EXTERNAL_ESTUDO;
  
/*
EXCLUSÕES
DROP TABLE EXTERNAL_ESTUDO  PURGE;
DROP DIRECTORY ESTUDO;
*/
---observação
/*
	BADFILE  --CASO SEJA CARREGADO NO FORMATO NÃO PREVISTO SERÁ APRESENTADO NESTE LOG
	SKIP 0 --NO CASO VOU DEIXAR ZERO (MAS SE O ARQUIVO COMEÇAR DA LINHA 2 PODEMOS ALTERAR COM ESSE COMANDO) POR DEFAULT É ZERO NÃO PRECISANDO COLOCAR

*/